Display previously logged WiFi names in a table.
octoposprime/op-mo-app pull request #23
Opened 2024-04-16 16:33 UTC by nedimtoymus

Issue #22

2024-04-29 12:11 UTC, FurkanTansel approved these changes

2024-05-02 08:56 UTC, Maraza25 commented
Make the changes on the latest version of the project and send it again

2024-05-02 08:56 UTC, Maraza25 requested changes
Make the changes on the latest version of the project and send it again

2024-05-16 09:14 UTC, FurkanTansel approved these changes

2024-05-24 07:02 UTC, closed without merging